### ISSUE TITLE
Исключить docker-compose как обязательный

### ISSUE THREAD

**Issue by dmitryburov** [yc-actions/yc-coi-deploy#128]
@nikolaymatrosov спасибо за решение для GA 👍

Вопрос следующий: 
в некоторых машинах я не использую спецификацию `docker-compose` и мне достаточно просто запустить новую версию контейнера из регистра. Но параметр `docker-compose-path` - обязательный, судя по схеме.
Это можно обойти, например значением `false` ? И тоже самое касается `user-data-path`, тк ВМ создаются через CLI или из консоли, но не через GA.

**Comment by nikolaymatrosov** [comment]
Если вы принесете pull request'ы с предложенными изменениями, то я их обязательно рассмотрю.

**Comment by dmitryburov** [comment]
Понял, благодарю
