### ISSUE TITLE
INVALID_ARGUMENT: Illegal argument subnet_id.zone_id

### ISSUE THREAD

**Issue by joker2017** [yc-actions/yc-coi-deploy#495]
Передаю ИД зоны, но почему-то ругается. 

  with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
          folder-id: ${{ secrets.YC_FOLDER_ID }}
          VM-name: ${{ secrets.YC_VM_NAME }}
          vm-service-account-id: ${{ secrets.YC_SERVICE_ACCOUNT_ID }}
          vm-subnet-id: ${{ secrets.YC_SUBNET_ID }}
          docker-compose-path: './yandex-cloud/docker-compose.yaml'
          user-data-path: './yandex-cloud/user-data.yaml'

исходный код https://github.com/joker2017/Miniwork/blob/main/.github/workflows/main5.yml

**Comment by nikolaymatrosov** [comment]
А подсеть точно с той зоне находится?

**Comment by joker2017** [comment]
<img width="509" alt="Снимок экрана 2023-11-04 085207" src="https://github.com/yc-actions/yc-coi-deploy/assets/25124537/5adc6583-57e0-40f7-b5e6-9bb6ea8bb78a">
